version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      POSTGRES_URL: "postgresql+asyncpg://postgres:root@db:5432/task_manager" # Подключение к базе данных через Docker-сеть
    depends_on:
      - db
    command: uvicorn app:app --host 0.0.0.0 --port 8000

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: